# docker-compose.yml
version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: vizinhanca-postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=meu_projeto
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: